Add IssuingAuthorization, IssuingBalance, IssuingBin, IssuingCard, IssuingHolder, IssuingInvoice, IssuingPurchase, IssuingTransaction, IssuingWithdrawal, Credit Note
starkinfra/sdk-dotnet pull request #2
Opened 2022-05-02 18:42 UTC by xavier-stark

2022-05-12 13:18 UTC, massaru-stark requested changes

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +{
No README do bank está com outro padrão de código:
```c#
foreach (IssuingBin IssuingBin in IssuingBins) {
```

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +        rules: new List<Dictionary<string, object>>() {
Faltou implementar a IssuingRule

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +foreach(IssuingHolder issuingHolder in issuingHolders)
Mesma coisa do padrão do { no final da linha, mudar em todos os outros lugares

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +    ).ToList();
Indentação está errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IssuingHolder.Log getLog = IssuingHolder.Log.Get("6299741604282368");
renomear getLog para log

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +List<IssuingCard> issuingCards = IssuingCard.Create(
renomear issuingCards para cards

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +foreach(IssuingCard issuingCard in issuingCards)
renomear issuingCard para card

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IEnumerable<IssuingCard> issuingCards = IssuingCard.Query(
Mesma coisa aqui

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +foreach(IssuingCard issuingCard in issuingCards)
Aqui também

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IssuingCard issuingCard = IssuingCard.Get("5353197895942144");
card

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IssuingCard issuingCard = IssuingCard.Get("5353197895942144");
mudar em todos outros lugares

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +### Delete an IssuingCard
Cancel and IssuingCard
Isso vai mudar no python tbm, mas já adianta aqui pra aproveitar o PR

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +### Delete an IssuingCard
Lembra de mudar no índice e anchor links também.

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +### Delete an IssuingCard
Fazer isso para todos outros recursos

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IEnumerable<IssuingPurchase> issuingPurchases = IssuingPurchase.Query(
renomear issuingPurchases -> purchase

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IEnumerable<IssuingPurchase> issuingPurchases = IssuingPurchase.Query(
Segue o mesmo racional para todos outros exemplos de recursos

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +Resource authorization = IssuingAuthorization.ParseContent(
Indentação está errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +
Deixa com um enter só

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +sendResponse(
Metade disso aqui tá com código de python, deixa igual o de cima
= -> : 
starkinfra.issuingauthorization.response -> IssuingAuthorization.Response

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +        tags= new List<string> { "other-id/456"},
Coloca um espaço entre o " e o }

{ "other-id/456" }

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +List<IssuingPurchase.Log> logs = IssuingPurchase.Log.Query(
Indentação errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IssuingInvoice issuingInvoice = IssuingInvoice.Create(
Indentação errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +Console.Write(getLog);
Da um enter entre essas linhas

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +List<IssuingInvoice.Log> logs = IssuingInvoice.Log.Query(
Indentação errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +IssuingWithdrawal issuingWithdrawal = IssuingWithdrawal.Create(
Indentação errada

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +Console.Write(issuingWithdrawal);
Da um enter entre essas linhas

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +Console.Write(getIssuingWithdrawal);
Enter entre essas linhas

2022-05-12 13:18 UTC, massaru-stark commented on README.md
> +Console.Write(getIssuingWithdrawal);
Faz a mesma coisa em todos que tiverem assim

2022-05-12 13:55 UTC, massaru-stark requested changes

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Tester", "Tester\Tester.csproj", "{E33C0E11-E4CD-4474-87CD-31DF77B3C99D}"
Pode confirmar se era pra ter commitado isso?

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +    ///     <item>Amount [long integer]: IssuingPurchase value in cents. Minimum = 0. ex: 1234 (= R$ 12.34)</item>
o type está errado, deixa só long

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +    ///     <item>IssuerAmount [long integer]: issuer amount. ex: 1234 (= R$ 12.34)</item>
o type está errado, deixa só long

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +    ///     <item>MerchantAmount [long integer]: merchant amount. ex: 1234 (= R$ 12.34)</item>
o type está errado, deixa só long

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        public float? Score { get; }
Precisa desse ? aqui?
Na linha debaixo também?

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        ///     <item>amount [long integer]: IssuingPurchase value in cents. Minimum = 0. ex: 1234 (= R$ 12.34)</item>
long

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        ///     <item>issuerAmount [long integer]: issuer amount. ex: 1234 (= R$ 12.34)</item>
long

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        public IssuingAuthorization(string id = null, string endToEndId = null, long amount = 0, int tax = 0, string cardId = null, long issuerAmount = 0, string issuerCurrencyCode = null, long merch
Quebra essa linha em várias

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        public IssuingAuthorization(string id = null, string endToEndId = null, long amount = 0, int tax = 0, string cardId = null, long issuerAmount = 0, string issuerCurrencyCode = null, long merch
O constructor de IssuongAuthorization não tem default, são obrigatórios

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        ///     <item>user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call</item>
Está no padrão de python, mudar isso em todos os lugares
```c#
<item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
```

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +
Tem um enter a mais

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +                        "\"tags\": [\"" + String.Join("\",\"", tags) + "\"]," +
Essa , no final vai quebrar

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        public static string Response(string status, long amount = 0, string reason = null, List<string> tags = null)
Tem que arrumar esses defaults aqui, vai quebrar do jeito que tá

2022-05-12 13:55 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +            return new IssuingAuthorization(id: id, endToEndId: endToEndId, amount: amount, tax: tax, cardId: cardId,
Indentação errada

2022-05-12 15:01 UTC, massaru-stark requested changes

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBalance/IssuingBalance.cs
> +    ///     <item>Id [string, default None]: unique id returned when IssuingBalance is created. ex: "5656565656565656"</item>
Da um replace all de None para null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBalance/IssuingBalance.cs
> +        ///     <item>id [string, default None]: unique id returned when IssuingBalance is created. ex: "5656565656565656"</item>
Tira o default de todos que forem return-only

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBin/IssuingBin.cs
> +        public IssuingBin(string id, string network, string settlement, string category, string client,
Indentação errada

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBin/IssuingBin.cs
> +        ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. Unlimited if None. ex: 35</item>
Unlimited if null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBin/IssuingBin.cs
> +            return new IssuingBin(id: id, network: network, settlement: settlement,
Indentação errada

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBin/IssuingBin.cs
> +
Tirar enter a mais

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +    ///     <item>DisplayName [string, default Null]: card displayed name. ex: "ANTHONY STARK"</item>
Null -> null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>rules [list of dictionaries, default Null]: [EXPANDABLE] list of card spending rules.</item>
lista de IssuingRules, precisa implementar

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +    ///     <item>DisplayName [string, default Null]: card displayed name. ex: "ANTHONY STARK"</item>
Faz um replace all

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>holder_id [string]: card holder unique id. ex: "5656565656565656"</item>
holderId

está no padrão de python, mudar todos de baixo para camelCase

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public IssuingCard(string holderName, string holderTaxId, string holderExternalId, string id = null, string holderId = null, string type = null,
Indentação errada

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +
Tirar um enter que ficou a mais

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>user [Organization/Project object]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
default null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +
Tirar um enter que ficou a mais

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>issuingCards [list of Dictionaries]: list of Dictionaries representing the IssuingCards to be created in the API</item>
Troca Dictionaries para dictionaries

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>user [Organization/Project object]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
default null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +
Tirar um enter a mais

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +
Tirar de todos outros lugares

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>user [Organization/Project object]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
Adicionar em todos os outros lugares

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>holder_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]</item>
holderIds

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +                    { "types", types},
coloca um espaço entre o types e o }

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +                    { "types", types},
mesma coisa para os demais

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>status [string]: you may cancel the IssuingCard by passing "canceled" in the status. ex: "canceled"</item>
You may block the IssuingCard by passing "blocked" or activate by passing "active" in the status

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>status [string]: you may cancel the IssuingCard by passing "canceled" in the status. ex: "canceled"</item>
default null

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static IssuingCard Update(string id, string status = null, string displayName = null, string rules = null, string tags = null, User user = null)
Rules não é string

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static IssuingCard Update(string id, string status = null, string displayName = null, string rules = null, string tags = null, User user = null)
Lista de IssuingRules

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        /// Parameters(required) :
Tem um espaço entre o ) e :

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        /// Parameters(optional) :
Mesma coisa aqui

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>user[Project object]: Project object. Not necessary if StarkInfra.User.Default was set before function call</item>
Falta Organization e default

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        /// Delete a IssuingCard entity
Trocar tudo de delete para cancel

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static IssuingCard Delete(string id, User user = null)
cancel

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +            return new IssuingCard(id : id, holderId: holderId, holderName: holderName, holderTaxId: holderTaxId,
Indentação errada

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +                Console.WriteLine(json);
👀

2022-05-12 15:01 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +                Console.WriteLine(json);
Da um find all e tira todos os prints que tiver

2022-05-16 17:33 UTC, massaru-stark requested changes

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static List<IssuingCard> Create(List<IssuingCard> IssuingCards, User user = null)
Precisa passar o expand aqui, dá uma olhada de como ficou no python

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>holder_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]</item>
holderIds

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>holder_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]</item>
Falta o default

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +        /// Every time a IssuingCard entity is modified, a corresponding IssuingCard.Log
an IssuingCard

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>rules [list of dictionaries, default null]: [EXPANDABLE] list of card spending rules.</item>
list of IssuingRule
precisa implementar aqui

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>tags [list of strings]: list of strings for tagging. ex: ["travel", "food"]</item>
Falta o default

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>tags [list of strings]: list of strings for tagging. ex: ["travel", "food"]</item>
Tem mais alguns sem o default abaixo

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static List<IssuingCard> Create(List<IssuingCard> IssuingCards, User user = null)
Parâmetro de método é em camelCase
IssuingCards -> issuingCards

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>user [Organization/Project objectm default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
"objectm"

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>after [DateTime or string, default null] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)</item>
Padrão de exemplo está o do Python, da um replace all de:
```datetime.date(2020, 3, 10)```
para:
```DateTime(2020, 3, 10)```

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        public static IEnumerable<IssuingCard> Query(List<string> types = null, int? limit = null,
Deixa padronizado a ordem dos parâmetros com os da DocString e dentro do método

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"</item>
Trocar os exemplos para: "active", "blocked", "expired" or "canceled"

2022-05-16 17:33 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"</item>
Trocar os exemplos para: "active", "blocked", "expired" or "canceled"

2022-05-16 20:28 UTC, massaru-stark requested changes

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +            /// Every time a IssuingCard entity is modified, a corresponding IssuingCard.Log
an IssuingCard
Faz um replace all

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +            ///     <item>type [string]: type of the IssuingCard event which triggered the log creation. ex: "processing" or "success"</item>
Tem que atualizar todos os types e status errados

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +            List<string> types = null, List<string> cardIds = null, User user = null)
Indentação errada

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +            List<string> types = null, List<string> cardIds = null, User user = null)
Nos outros métodos também estão errados

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +        public static List<IssuingHolder> Create(List<IssuingHolder> IssuingHolders, User user = null)
Parâmetro em camelCase

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +        ///     <item>status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"</item>
Arruma a ordem de parâmetros nas docstrings, declaração e corpo do método em todos os query() e page() de recursos e logs

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +                    { "status", status},
coloca um espaço antes dos } pra ficar chique

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +        ///     <item>expand [list of strings, default null]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]</item>
securityCode em camelCase
Faz um find all em "_" e muda o que tiver errado

2022-05-16 20:28 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +        int? limit = null, DateTime? after = null, DateTime? before = null, string status = null, List<string> tags = null,
Indentação errada

2022-05-16 22:04 UTC, massaru-stark requested changes

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingInvoice/Log.cs
> +        /// Every time a IssuingInvoice entity is modified, a corresponding IssuingInvoice.Log
Replace all de " a Issuing" por " an Issuing"

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingInvoice/Log.cs
> +            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: "success" or "failed"</item>
Nos exemplos de listas, coloca uma lista mesmo:
["parametro" or "outroParametro"]

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingPurchase/IssuingPurchase.cs
> +    /// The IssuingPurchase object displays the information of the cards created in your Workspace.
Descrição errada. Alterar para:
```
Displays the IssuingPurchase objects created in your Workspace.
```

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingPurchase/IssuingPurchase.cs
> +        string tax = null, long issuerAmount = 0, string issuerCurrencyCode = null,
Indentação errada

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingPurchase/IssuingPurchase.cs
> +        ///     <item>status [string, default null]: filter for status of retrieved objects. ex: "approved", "canceled", "denied", "confirmed" or "voided"</item>
List of strings

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingPurchase/IssuingPurchase.cs
> +        ///     <item>status [string, default null]: filter for status of retrieved objects. ex: "approved", "canceled", "denied", "confirmed" or "voided"</item>
List of strings

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingPurchase/Log.cs
> +            ///     <item>errors [list of strings]: list of errors linked to this BoletoPayment event.</item>
list of errors linked to this IssuingPurchase.

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingTransaction/IssuingTransaction.cs
> +        ///     <item>amount [long integer]: IssuingTransaction value in cents. ex: 1234 (= R$ 12.34)</item>
[long]

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingTransaction/IssuingTransaction.cs
> +        ///     <item>ids [list of strings, default [], default null]: purchase IDs</item>
Tem dois defaults

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingTransaction/IssuingTransaction.cs
> +        ///     <item>ids [list of strings, default [], default null]: purchase IDs</item>
Dois defaults

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingWithdrawal/IssuingWithdrawal.cs
> +        /// The IssuingWithdrawal object displays the information of the cards created in your Workspace.
```The IssuingWithdrawal objects created in your Workspace return cash from your Issuing balance to your Banking balance.```

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingWithdrawal/IssuingWithdrawal.cs
> +        ///     <item>issuingWithdrawals [list of Dictionaries]: list of Dictionaries representing the IssuingWithdrawals to be created in the API</item>
renomear issuingWithdrawals para withdrawal

2022-05-16 22:04 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingWithdrawal/IssuingWithdrawal.cs
> +        /// Create IssuingWithdrawals
Tem que trocar esse método pra postSingle

2022-05-16 22:47 UTC, massaru-stark requested changes

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfra/StarkInfra.csproj
> +    <None Remove="PixBalance %28copy%29\" />
👀

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfra/Utils/Checks.cs
> +            List<string> environments = new List<string>() { "production", "sandbox", "development" };
👀

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfra/Utils/Request.cs
> +            if (user.Environment == "development")
👀

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingAuthorization.cs
> +        public readonly User user = TestUser.SetDefaultProject();
Precisa adicionar o teste de invalidSignature

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingAuthorization.cs
> +        string valid_signature = "MEUCIBxymWEpit50lDqFKFHYOgyyqvE5kiHERi0ZM6cJpcvmAiEA2wwIkxcsuexh9BjcyAbZxprpRUyjcZJ2vBAjdd7o28Q=";
Renomear esses parâmetros pra camelCase

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingBalance.cs
> +}
Adicionar uma linha em branco no final do arquivo

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingBin.cs
> +                Debug.Write(IssuingBin);
Pode deixar só o TestUtils.Log(IssuingBin);

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingBin.cs
> +                Debug.Write(IssuingBin);
O mesmo pra todos os outros testes, faz aquele replace all

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +            string expected = "active";
Esses nomes de varáveis estão bem estranhos

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +            Assert.NotNull(issuingCards.First().ID);
Você já extraiu esse cara antes, pode fazer issuingCard.ID

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +
Tirar essas linhas em branco entre os }

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +                holderExternalId: "3456"
Precisa implementar um método para buscar um IssuingHolder, copia o do Python

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCardLog.cs
> +                ).ToList();
Arrumar indentação

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCardLog.cs
> +}
Adicionar uma linha em branco no final do arquivo

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolder.cs
> +            string expectedStatus = "blocked";
Renomear essas variáveis

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolder.cs
> +            IssuingHolder getIssuingHolder = IssuingHolder.Get(id: issuingHolder.ID);
Os nomes dessas variáveis não ficaram legais, copia o padrão do python!

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolder.cs
> +                externalId : "457",
Precisa ter alguma aleatoriedade nesse externalId

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolderLog.cs
> +                ).ToList();
Arrumar a indentação

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolderLog.cs
> +            IssuingHolder.Log getLog = IssuingHolder.Log.Get(id: logs.First().ID);
Atribui essas entidades que você pega pelo .First() em uma variável, aí fica bem mais fácil pra acessar elas!

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingHolderLog.cs
> +}
Adicionar uma linha em branco no final do arquivo!

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingInvoiceLog.cs
> +}
Adicionar uma linha em branco no final do file!

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingPurchase.cs
> +            IssuingPurchase issuingPurchase = IssuingPurchase.Get("5642359077339136");
Esse teste está fora do padrão, faz um query(limit=1) e depois faz o get() pelo id que retornou no query

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingPurchaseLog.cs
> +}
Linha em branco no final do file

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingTrasaction.cs
> +            IssuingTransaction issuingTransaction = IssuingTransaction.Get("6539944898068480");
Alterar para o padrão de python

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingWithdrawal.cs
> +            IssuingWithdrawal issuingWithdrawal = IssuingWithdrawal.Create( Example() );
Tem dois espaços entre Example() e )

2022-05-16 22:47 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/StarkInfraTests.csproj
> +  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
Certeza que é pra commitar isso?

2022-05-16 22:54 UTC, massaru-stark requested changes

2022-05-16 22:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingBalance/IssuingBalance.cs
> +    ///     <item>Id [string, default null]: unique id returned when IssuingBalance is created. ex: "5656565656565656"</item>
Padrão de dotnet é ID

2022-05-16 22:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/Log.cs
> +            public static IEnumerable<Log> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
Adicionar ids na busca

2022-05-16 22:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/Log.cs
> +            public static (List<Log> page, string pageCursor) Page(string cursor = null, int? limit = null, DateTime? after = null,
Adicionar ids na busca

2022-05-16 22:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingInvoice/Log.cs
> +
Falta implementar o get()

2022-05-20 09:54 UTC, massaru-stark requested changes

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingAuthorization/IssuingAuthorization.cs
> +        public static string Response(string status, long amount = 0, string reason = null, List<string> tags = null)
Esse método ainda está errado, testa ele printando a string que retorna

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingCard.cs
> +        ///     <item>status [string]: You may block the IssuingCard by passing "blocked" or activate by passing "active" in the status</item>
Ainda falto o default no status

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/IssuingRule.cs
> +        ///     <item>Id [string, default null]: unique id returned when IssuingRule is created. ex: "5656565656565656"</item>
Subresource não tem ID

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingCard/Log.cs
> +            List<string> types = null, List<string> cardIds = null, User user = null)
Ainda errado

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingHolder/IssuingHolder.cs
> +        public static List<IssuingHolder> Create(List<IssuingHolder> IssuingHolders, List<string> expand = null, User user = null)
Nome do parâmetro "IssuingHolders" -> "issuingHolders"

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfra/IssuingWithdrawal/IssuingWithdrawal.cs
> +        public static IssuingWithdrawal Create(IssuingWithdrawal IssuingWithdrawal, User user = null)
Trocar o nome do método "IssuingWithdrawal" para camelCase

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +            IssuingHolder holder = IssuingHolder.Query(limit: 101, status: "active").ToList().First();
Limit 1

2022-05-20 09:54 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/IssuingCard.cs
> +
Indentação e espaços em branco ainda errados

2022-05-26 15:43 UTC, joaogpw-stark approved these changes

2022-05-26 21:34 UTC, joaogpw-stark approved these changes

2022-05-26 21:39 UTC, merged