Pix Claim, Pix Key, Pix Director, Pix Chargeback, Pix Infraction, Pix Domain, Pix Reversal, Credit Note
starkinfra/sdk-dotnet pull request #3
Opened 2022-05-13 20:35 UTC by xavier-stark

2022-05-20 10:51 UTC, massaru-stark requested changes

2022-05-20 10:51 UTC, massaru-stark commented on CHANGELOG.md
> +- PixInfraction resource for Indirect and Direct Participants
PixDirector resource for Direct Participants

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        public static IEnumerable<CreditNote> Query(string status = null, List<string> types = null, List<string> holderIds = null,
Parâmetros errados

limit=None, status=None, tags=None, ids=None, after=None, before=None, user=None

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        public static IEnumerable<CreditNote> Query(string status = null, List<string> types = null, List<string> holderIds = null,
Mesma coisa no page

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        ///     <item>deleted CreditNote object</item>
Canceled

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice.cs
> +        ///     <item>due [DateTime, Date or string, default now + 2 days]: Invoice due date in UTC ISO format. ex: ~U[2021-03-26 19:32:35.418698Z] for immediate invoices and ~D[2020-10-28] for sched
Due é optional

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Transfer.cs
> +
Falta description, fee, created, updated, updated, transactionIds

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixChargeback/PixChargeback.cs
> +    /// A reversal request can be created when fraud is detected on a transaction or a system malfunction
A Pix chargeback

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixChargeback/PixChargeback.cs
> +
Falta implementar o create da lista de dicionários

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixChargeback/PixChargeback.cs
> +        /// Delete a PixChargeback entity
Cancel, muda nos outros também

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixDirector/PixDirector.cs
> +        /// Create PixDirectors
Trocar para o padrão de postSingle

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixDomain/PixDomain.cs
> +        public List<Dictionary<string, object>> Content { get; }
Content é lista de certificates, copia do Python

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixDomain/PixDomain.cs
> +        public List<Dictionary<string, object>> Content { get; }
Subresource

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixDomain/PixDomain.cs
> +                    {"limit", null }
Precisa disso?

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixKey/PixKey.cs
> +        /// Create PixKeys
Trocar para o padrão de postSingle

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/Utils/Checks.cs
> +            List<string> environments = new List<string>() { "production", "sandbox", "development" };
Tirar development

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/Utils/Rest.cs
> +using System.Diagnostics;
Acho que não era pra ter essa linha

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/Webhook/Webhook.cs
> +        ///     <item>report [Webhook object]: Webhook object to be created in the API.</item>
Isso é de PixReport, cópia o de Python

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfra/Webhook/Webhook.cs
> +        /// Retrieve the PixInfraction object linked to your Workspace in the Stark Infra API using its id.
PixInfraction?

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/CreditNote.cs
> +            Assert.NotNull(creditNotes.First().ID);
Usa o creditNote que extraiu antes

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/CreditNoteLog.cs
> +                Debug.Write(log);
Pode tirar

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/CreditNoteLog.cs
> +                Debug.Write(log);
Mesma coisa pros outros

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixDirector.cs
> +            );
Copia os exemplos de Python

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixDomain.cs
> +                TestUtils.Log(PixDomain);
Coloca assert not null do ID aqui

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixInfraction.cs
> +                referenceId: "E20018183202204951450u34sDGd19lz",
Copia o gerador de Python

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixKey.cs
> +            );
Copia o gerador de Python

2022-05-20 10:51 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixKeyLog.cs
> +            Debug.Write(getLog);
Da pra melhorar esse teste

2022-05-20 20:19 UTC, massaru-stark commented on StarkInfra/StarkInfra/PixDomain/PixDomain.cs
> +    ///    <item>Domain [string]: current active domain (URL) of the Pix participant.</item>
Não é Domain, renomeia pra Name
Copia as docstrings de python

2022-05-20 20:23 UTC, massaru-stark commented on StarkInfra/StarkInfraTests/PixDirector.cs
> +            );
Troca pelo menos o name pra "Jon Snow"

2022-05-20 20:33 UTC, massaru-stark commented
Ainda falta adicionar as correções do sheets

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +    - [Credit Note](#credit-note)
Copia e cola isso de python, a indentação tá toda errada. 
Arruma anchor link, da uma olhada em python

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +    keyIds: new List<string> { "304b33c2-3867-478d-864a-efa155af0d1d" }
Coloca uma id bonitinha ai, evo é muito feio

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +
Linha a mais aqui

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +
Tem em vários lugares do readme isso, da um search all no readme para arrumar

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +        limit: 1,
indentação errada

2022-05-24 00:28 UTC, joaogpw-stark commented on README.md
> +                    new Invoice(
indentação ?

2022-05-24 00:28 UTC, joaogpw-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        ///     <item>payment [Payment object]: Payment object to be created and sent to the credit receiver. ex: payment=Payment()</item>
1) Não existe payment object
2) Pode ser gym diccionario tameme, isso na invoice e signer tiambem
3) exemplo também esta errado

2022-05-24 00:28 UTC, joaogpw-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        ///     <item>interest [float]: yearly effective interest rate of the credit note, in percentage. ex: 12.5</item>
Faltando atributo

2022-05-24 00:28 UTC, joaogpw-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        /// Parameters (optional):
faltando parâmetro conditionally required

2022-05-24 00:28 UTC, joaogpw-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +
Linha a mais

2022-05-24 00:28 UTC, joaogpw-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        private static List<Invoice> ParseInvoiceJson(dynamic json)
ParseInvoiceJson -> ParseInvoices, mesma coisa pra os outros

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        /// Parameters (optional):
Falta o paymentType, ele é conditionally required
Copia o padrão do Python

2022-05-25 20:37 UTC, massaru-stark commented on README.md
>  Your initial balance is zero. For many operations in Stark Infra, you'll need funds
Isso ta bem errado, imagino que esteja assim em todos os SDKs

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +    parameters: parameters
Talvez definir o Dictionary aqui mesmo

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +    patchData: patchData
Mesma lógica aqui

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +
Enter a mais

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +    limit: 1,
Não é melhor aumentar todos esses limits pra pelo menos 10?

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +    patchData: patchData
Mesma coisa do Dictionary aqui

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +                 )
Talvez adicionar um exemplo de descriptions

2022-05-25 20:37 UTC, massaru-stark commented on README.md
> +        "signer"
Agrupar as subscriptions por produto e adicionar os demais de Pix

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/CreditNote.cs
> +        ///     <item>PaymentType [string]:  payment type, inferred from the payment parameter if it is not a dictionary. ex: "transfer"</item>
Ta com 2 espaços entre o : e o payment

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice/Invoice.cs
> +    /// Invoice object to be issued after contract signature and paid by the credit receiver.
Invoice issued after the contract is signed, to be paid by the credit receiver.

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice/Invoice.cs
> +        /// Invoice object to be issued after contract signature and paid by the credit receiver.
Mudar aqui também

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice/Invoice.cs
> +        ///     <item>discounts [list of CreditNote.Invoice.Discount objects, default null]: list of Discount objects or dictionaries with "percentage":float and "due":datetime.datetime or string pai
Tirar o default

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice/Discount.cs
> +
Tirar esse enter a mais

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Invoice/Description.cs
> +
Tirar esse enter

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/CreditNote/Transfer.cs
> +        ///     <item>externalId [string, default null]: url safe string that must be unique among all your transfers. Duplicated external_ids will cause failures. By default, this parameter will blo
retirar default dos return-only

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/Event/Event.cs
>      ///     <item>Subscription [string]: service that triggered this event. ex: "transfer", "utility-payment"</item>
Trocar os exemplos de subscription para algum de infra

2022-05-25 20:37 UTC, massaru-stark commented on StarkInfra/StarkInfra/Event/Event.cs
>          ///     <item>subscription [string]: service that triggered this event. ex: "transfer", "utility-payment"</item>
Mesma coisa aqui

2022-05-26 17:26 UTC, massaru-stark approved these changes

2022-05-26 17:27 UTC, merged